# Generated by Django 5.0.14 on 2026-07-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('bot', 'Bot'), ('group', 'Group'), ('user', 'User')], db_index=True, max_length=10)),
                ('scope_id', models.PositiveIntegerField(blank=True, help_text='Group/User ID, bot uchun NULL', null=True)),
                ('period', models.CharField(default='daily', max_length=10)),
                ('data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['scope', 'scope_id', 'period', 'generated_at'], name='statistics__scope_8c6aca_idx')],
            },
        ),
    ]
