# Generated by Django 5.0.14 on 2026-07-22 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('mentor', 'Mentor'), ('group_owner', 'Group Owner'), ('user', 'User')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('full_name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_reason', models.CharField(blank=True, max_length=255)),
                ('can_create_group', models.BooleanField(default=False, help_text='Admin tomonidan beriladigan ruxsat')),
                ('last_active_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_banned', 'is_premium'], name='users_user_is_bann_f6c55f_idx'), models.Index(fields=['last_active_at'], name='users_user_last_ac_44cc2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='groups.group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.user')),
            ],
            options={
                'unique_together': {('user', 'role', 'group')},
            },
        ),
    ]
