# Generated by Django 5.0.14 on 2026-07-24 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_reminders', models.BooleanField(default=True)),
                ('homework_reminders', models.BooleanField(default=True)),
                ('inactivity_reminders', models.BooleanField(default=True)),
                ('streak_reminders', models.BooleanField(default=True)),
                ('daily_report', models.BooleanField(default=True)),
                ('weekly_report', models.BooleanField(default=True)),
                ('announcements', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('deadline', 'Deadline reminder'), ('homework', 'Homework reminder'), ('inactivity', 'Inactivity reminder'), ('streak', 'Streak reminder'), ('report', 'Productivity report'), ('announcement', 'Announcement'), ('system', 'System notification')], max_length=20)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.user')),
            ],
            options={
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_d8d933_idx')],
            },
        ),
    ]
